---
- name: postgres vagrant user
  sudo: yes
  # sudo_user: postgres
  # postgresql_user: name=vagrant role_attr_flags=SUPERUSER state=present
  shell: su - postgres -c 'createuser -s vagrant'
  ignore_errors: true

- name: postgres vagrant default database
  # sudo_user: postgres
  # postgresql_db:
  #   name=vagrant
  #   encoding="UTF-8"
  #   lc_collate="en_US.UTF-8"
  #   lc_ctype="en_US.UTF-8"
  #   template="template0"
  #   owner="vagrant"
  #   state=present
  shell: createdb vagrant
  ignore_errors: true
