---
- name: create source directory
  sudo: true
  shell: mkdir -p /usr/local/src creates=/usr/local/src

- name: clone ruby-install
  sudo: true
  git: repo=https://github.com/postmodern/ruby-install.git dest=/usr/local/src/ruby-install update=yes

- name: install ruby-install
  sudo: true
  command: make install chdir=/usr/local/src/ruby-install creates=/usr/local/bin/ruby-install

- name: install rubies
  sudo: true
  command: /usr/local/bin/ruby-install ruby {{ item.ruby }} creates=/opt/rubies/ruby-{{ item.ruby }}
  with_items:
    - ruby: 2.2.0

- name: install most needed gems
  sudo: true
  command: /opt/rubies/ruby-{{ item[0] }}/bin/gem install {{ item[1] }} --no-user-install --no-document
  with_nested:
    - [ '2.2.0' ]
    - [ 'bundler', 'pry', 'pry-byebug' ]

- name: clone chruby
  sudo: true
  git: repo=https://github.com/postmodern/chruby.git dest=/usr/local/src/chruby update=yes

- name: install chruby
  sudo: true
  command: make install chdir=/usr/local/src/chruby creates=/usr/local/share/chruby

- name: install /etc/profile.d/chruby.sh
  sudo: true
  copy: src=files/chruby.sh dest=/etc/profile.d/chruby.sh owner=root group=root mode=0644



  